### ISSUE TITLE
Running server results in an insta crash.

### ISSUE THREAD

**Issue by ub0nFPS** [codehz/ElementZero#161]
So, I uploaded my server as a zip onto the cloud, to be run on my new machine when I got it.
I get the machine, download the zip, extract it, then attempt to run it, then get a crash. No idea why.
Error output:

```System.NullReferenceException: Object reference not set to an instance of an object.
   at VellumZero.DiscordBot.SendMessage(String text)
   at VellumZero.VellumZero.<Initialize>b__24_4(Object sender, EventArgs e)
   at Vellum.Automation.ProcessManager.ProcessExited(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(_ThreadPoolWaitOrTimerCallback helper, Boolean timedOut)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at VellumZero.DiscordBot.SendMessage(String text)
   at VellumZero.VellumZero.<Initialize>b__24_4(Object sender, EventArgs e)
   at Vellum.Automation.ProcessManager.ProcessExited(Object sender, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(_ThreadPoolWaitOrTimerCallback helper, Boolean timedOut)```

**Comment by ub0nFPS** [comment]
that is output from vellum, if I attempt to launch the server from modded_bedrock.exe it instantly closes, with no errors logged

**Comment by ub0nFPS** [comment]
![image](https://user-images.githubusercontent.com/61366452/97807699-883a0600-1c1f-11eb-8364-4f72da1cbea4.png)
